53:Translations round 4
mchev/blinest pull request #54
Opened 2023-03-07 20:32 UTC by Ckrapock

2023-03-07 20:41 UTC, mchev requested changes

2023-03-07 20:41 UTC, mchev commented on resources/js/Components/DonationBanner.vue
> +        {{ __('Blinest is ') }}<span class="font-bold">{{ __('free and ad-free') }}</span>{{ __('. To keep it going, it needs your support.') }}<br><span class="italic"> {{ __('If everyone gave 1€, i
- Traduction non nécessaire sur ce fichier.
- Double version présente dans le commit

2023-03-07 20:41 UTC, mchev commented on resources/js/Pages/Moderation/partials/TrashedMessages.vue
> +                <span class="text-xs text-neutral-500">{{ __('Creation:') }} {{ message.created_at }}</span>
Created at

2023-03-07 20:41 UTC, mchev commented on resources/js/Pages/Moderation/partials/TrashedMessages.vue
> +                <span class="text-xs text-neutral-500">{{ __('Deletion:') }} {{ message.deleted_at }}</span>
Deleted at

2023-03-07 20:41 UTC, mchev commented on resources/lang/fr/fr.json
> +    "free and ad-free":"gratuit et sans publicité",
Supprimer les traductions concernant les dons. Pas nécessaire d'alourdir ce fichier pour un élément qui ne sera visible que quelques jours dans l'année.

2023-03-07 23:08 UTC, Ckrapock commented
Everything fixed I believe !

2023-03-12 17:23 UTC, mchev approved these changes

2023-03-12 17:23 UTC, merged